chore: initial update to next 13
PaperMC/website pull request #74
Opened 2023-09-24 21:51 UTC by darbyjack

2023-09-26 06:10 UTC, Cubxity requested changes

2023-09-26 06:10 UTC, Cubxity commented on src/pages/index.tsx
> +              sizes="100vw"
This size is unreasonably large for some displays. Consider using media conditions. This applies to other images too.

2023-09-26 06:10 UTC, Cubxity commented on src/pages/index.tsx
> +                objectFit: "cover",
Use tailwind's utility class instead. This applies to other images too.

2023-10-05 18:26 UTC, MiniDigger approved these changes
lgtm, cant comment on the link changes but everything looks good to me on vercel

2023-10-09 07:07 UTC, merged