Update Team
PaperMC/website pull request #85
Opened 2023-12-08 19:00 UTC by notTamion

i noticed that lulu and noah were missing in the dev team so i just added everyone i found missing based of discord roles. So if i wrongfully removed/added someone thats because they are either not on the discord or don't got the role. if i missed someone or your internal team structure is different please tell me.

2023-12-08 19:05 UTC, powercasgamer requested changes

2023-12-08 19:05 UTC, powercasgamer commented on assets/data/team.json
> -      },
Five is still a velocity dev.

2023-12-08 19:16 UTC, notTamion commented
i couldn't find his github lol. could you send it me rq?

2023-12-09 19:52 UTC, NoahvdAa approved these changes

2023-12-09 20:25 UTC, olijeffers0n approved these changes
LGTM

2023-12-10 12:04 UTC, merged