feat: Add tags to team members
PaperMC/website pull request #90
Opened 2024-01-19 11:05 UTC by olijeffers0n

A POC of what this could look like. If it is liked then I can add more tags

2024-01-19 17:13 UTC, MiniDigger approved these changes
nitpick, lgtm otherwise

2024-01-19 17:13 UTC, MiniDigger commented on src/pages/team.tsx
> +                        member.tags.map((tag) => (
```suggestion
                      {member.tags?.map((tag) => (
```

2024-01-20 03:15 UTC, kashike requested changes

2024-01-20 03:15 UTC, kashike commented on assets/data/team.json
> +            "description": "Handles Paper's documentation"
```suggestion
            "description": "Handles documentation for PaperMC projects"
```

2024-01-22 16:11 UTC, olijeffers0n commented on assets/data/team.json
> +            "description": "Handles Paper's documentation"
Fixed

2024-01-26 20:20 UTC, MiniDigger commented on src/pages/team.tsx
> +                    <div className="flex-1 flex items-center">
```suggestion
                    <div className="flex items-center">
```

2025-07-12 19:51 UTC, MiniDigger commented
we couldn't really agree on if we want this (and what tags who would get), so ill close this
thanks anyways

2025-07-12 19:51 UTC, closed without merging