feat: announce waterfall eol
PaperMC/website pull request #96
Opened 2024-03-01 18:44 UTC by MiniDigger

2024-03-02 21:03 UTC, kashike requested changes

2024-03-02 21:03 UTC, kashike commented on src/components/layout/SoftwareDownload.tsx
> +            Waterfall has been archived! It is no longer maintained or
This message would show if a different project became `archived`. That's no good.

2024-03-08 14:06 UTC, notTamion commented on src/components/layout/SoftwareDownload.tsx
> +          <div className="text-center px-4 py-8 -mt-16 font-bold bg-red-400 dark:bg-red-500 shadow-md rounded w-full">
```suggestion
          <div className="text-center px-4 py-8 -mt-16 font-bold bg-red-400 dark:bg-red-500 shadow-md rounded-lg w-full">
```
Makes it a bit rounder which looks better imo

2024-03-26 16:19 UTC, MiniDigger commented on src/components/layout/SoftwareHeader.tsx
> +      <div className="text-center px-4 py-8 -mt-16 font-bold bg-red-400 dark:bg-red-500 shadow-md rounded w-full">
```suggestion
      <div className="text-center px-4 py-8 -mt-16 font-bold bg-red-400 dark:bg-red-500 shadow-md rounded-lg w-full">
```

2024-03-26 16:22 UTC, merged